# CXX = g++
# CXXFLGAS = -g3 -Wall --std=c++11

# all: selection_sort

# selection_sort: selection_sort.cpp
# 	$(CXX) $(CXXFLGAS) selection_sort.cpp -o selection_sort
CXX = g++
CPPFLAGS = --std=c++11 -Wall -g

all: circular_list_int

selection_sort: circular_list_int.cpp circular_list_int.h
	$(CXX) $(CPPFLAGS) circular_list_int.cpp -o circular_list_int